#!/usr/bin/env python3
"""
Typing Lab - MEGA Word Pool Generator
Target: 10,000+ words from all sources
"""

import json

# Start with current words
with open('words.json', 'r') as f:
    current = json.load(f)

# Massive expansion with more words
mega_words = []

# Tech/Programming (500+ more)
mega_words.extend([
    # Languages & Frameworks
    "angular", "assembly", "backend", "bash", "bootstrap", "c", "clojure", "cobol",
    "coffeescript", "cpp", "csharp", "dart", "django", "dotnet", "elixir", "elm",
    "erlang", "express", "fastapi", "flask", "flutter", "fortran", "gatsby", "golang",
    "graphql", "groovy", "haskell", "ionic", "java", "javascript", "jquery", "julia",
    "kotlin", "laravel", "lisp", "lua", "matlab", "nest", "nextjs", "nodejs", "nuxt",
    "objective", "pascal", "perl", "php", "postgresql", "prolog", "python", "rails",
    "react", "redux", "ruby", "rust", "sass", "scala", "scheme", "scratch", "spring",
    "sql", "svelte", "swift", "symfony", "tailwind", "typescript", "unity", "unreal",
    "visual", "vue", "vuejs", "webpack", "xamarin",
    
    # Tools & Platforms
    "airflow", "ansible", "apache", "aws", "azure", "babel", "bamboo", "bitbucket",
    "chef", "circleci", "cloudflare", "confluence", "consul", "cypress", "datadog",
    "deno", "digitalocean", "discord", "docker", "dropbox", "eclipse", "elastic",
    "electron", "evernote", "figma", "firebase", "gatsby", "gerrit", "github", "gitlab",
    "google", "gradle", "grafana", "graphql", "grunt", "gulp", "heroku", "intellij",
    "jenkins", "jira", "kafka", "kubernetes", "linode", "maven", "mongodb", "mysql",
    "nagios", "netlify", "nginx", "notion", "npm", "oracle", "pandas", "postman",
    "prometheus", "puppet", "pytorch", "rabbitmq", "redis", "redux", "rollbar",
    "salesforce", "selenium", "sentry", "slack", "snowflake", "splunk", "sqlite",
    "stripe", "subversion", "tableau", "telegram", "tensorflow", "terraform", "travis",
    "trello", "twilio", "ubuntu", "vault", "vercel", "vscode", "webpack", "wordpress",
    "yarn", "zendesk", "zoom",
    
    # Concepts
    "abstraction", "accessor", "adapter", "agnostic", "allocation", "ancestor",
    "anonymous", "antipattern", "append", "argument", "array", "assertion", "assign",
    "asynchronous", "authentication", "authorization", "automation", "availability",
    "backend", "backward", "bandwidth", "baseline", "batch", "benchmark", "binding",
    "bitwise", "blackbox", "blob", "boolean", "bottleneck", "bracket", "breakpoint",
    "broadcast", "browser", "bucket", "bugfix", "build", "bundle", "bytecode",
    "cache", "callback", "camelcase", "capacity", "cascade", "casting", "catalog",
    "certificate", "changelog", "channel", "character", "charset", "checkbox", "checkpoint",
    "checksum", "chunk", "cipher", "circular", "claim", "class", "clause", "cleanup",
    "cleartext", "client", "clone", "closure", "cluster", "codec", "cohesion",
    "collection", "collision", "column", "command", "comment", "commit", "compatibility",
    "compilation", "compiler", "complement", "complexity", "component", "composite",
    "compression", "computation", "concatenate", "concurrency", "condition", "configuration",
    "connection", "consistency", "console", "constant", "constraint", "constructor",
    "container", "content", "context", "continuous", "contributor", "controller",
    "conversion", "cookie", "coordinate", "correlation", "coupling", "coverage",
    "crawl", "credentials", "cron", "crossorigin", "crud", "cryptographic", "cursor",
    "daemon", "dashboard", "database", "datatype", "datetime", "deadlock", "deallocate",
    "debug", "decimal", "declaration", "decode", "decrement", "decrypt", "dedicate",
    "default", "definition", "delegate", "deletion", "delimiter", "dependency",
    "deployment", "deprecate", "dequeue", "derivative", "deserialize", "desktop",
    "destructor", "development", "devops", "diagnostics", "dictionary", "digest",
    "digital", "dimension", "directory", "disconnect", "dispatch", "displacement",
    "display", "distribution", "divider", "documentation", "domain", "dropdown",
    "duplicate", "duration", "dynamic", "ecosystem", "editable", "editor", "efficient",
    "element", "embedded", "emoji", "emulator", "encapsulation", "encode", "encrypt",
    "endpoint", "engine", "entity", "entry", "enumerate", "environment", "equality",
    "equation", "error", "escape", "ethernet", "evaluate", "event", "exception",
    "exclude", "executable", "execution", "explicit", "exploit", "exponential",
    "export", "expression", "extension", "external", "extract", "facade", "factory",
    "failover", "fallback", "favicon", "feature", "feedback", "fetch", "field",
    "fifo", "filesystem", "filter", "finally", "fingerprint", "firewall", "firmware",
    "fixture", "flag", "flatmap", "flexibility", "floating", "flowchart", "folder",
    "footer", "foreign", "fork", "format", "formula", "forward", "framework",
    "frontend", "fulfilled", "fullstack", "function", "functional", "garbage",
    "gateway", "generator", "generic", "getter", "gigabyte", "global", "gradient",
    "graphical", "gridview", "handler", "handshake", "hardware", "hash", "hashmap",
    "hashtable", "header", "heap", "heuristic", "hexadecimal", "hierarchy", "highlight",
    "homepage", "horizontal", "hostname", "hotfix", "hover", "html", "http", "https",
    "hyperlink", "hypertext", "hyphen", "icon", "identifier", "identity", "idle",
    "iframe", "immutable", "implementation", "implicit", "import", "increment",
    "indentation", "index", "indicator", "infinite", "inheritance", "initial",
    "initialization", "injection", "inline", "inner", "input", "insertion", "instance",
    "instantiate", "instruction", "integer", "integrate", "integration", "integrity",
    "intellisense", "interactive", "interface", "intermediary", "internal", "interpolation",
    "interpreter", "interrupt", "interval", "intranet", "introspection", "invocation",
    "invoke", "iterable", "iteration", "iterator", "javascript", "json", "junction",
    "justify", "kernel", "keyboard", "keyframe", "keymap", "keyword", "kilobyte",
    "label", "lambda", "landscape", "language", "latency", "layout", "legacy",
    "legend", "length", "lexical", "library", "license", "lifecycle", "lightweight",
    "limitation", "linear", "linker", "literal", "loader", "localhost", "location",
    "lock", "logarithmic", "logic", "login", "logout", "lookup", "loop", "lowercase",
])

# Common verbs and adjectives (1000+)
mega_words.extend([
    "abandon", "abbreviate", "abolish", "abort", "abridge", "absolute", "abstain",
    "abstract", "abundant", "accelerate", "accent", "accept", "access", "accident",
    "acclaim", "accommodate", "accompany", "accomplish", "accord", "account", "accumulate",
    "accurate", "accuse", "achieve", "acknowledge", "acquire", "across", "active",
    "actual", "acute", "adamant", "adapt", "adequate", "adhere", "adjacent", "adjust",
    "administer", "admire", "admit", "adopt", "adore", "advance", "advantage", "adventure",
    "adverse", "advertise", "advise", "advocate", "aesthetic", "affect", "affiliate",
    "affirm", "afford", "afraid", "after", "again", "against", "agent", "aggregate",
    "aggressive", "agile", "agitate", "agree", "ahead", "alert", "algorithm", "alien",
    "align", "alike", "alive", "allocate", "allow", "alloy", "almost", "alone",
    "along", "aloud", "alpha", "already", "alter", "alternate", "alternative", "although",
    "altitude", "always", "amaze", "ambient", "ambiguous", "ambitious", "ameliorate",
    "amend", "amiable", "among", "amount", "ample", "amplify", "amuse", "analogous",
    "analyze", "ancestor", "ancient", "anger", "angle", "angry", "anguish", "animate",
    "announce", "annoy", "annual", "anomaly", "anonymous", "another", "answer", "anticipate",
    "antique", "anxious", "apart", "apologize", "apparent", "appeal", "appear", "append",
    "appetite", "applaud", "apply", "appoint", "appreciate", "approach", "appropriate",
    "approve", "approximate", "arbitrary", "arcade", "architect", "archive", "ardent",
    "arduous", "argue", "arise", "arithmetic", "arrange", "arrest", "arrive", "arrogant",
    "arrow", "article", "articulate", "artificial", "artist", "ascend", "ascertain",
    "ashamed", "aside", "aspect", "aspire", "assemble", "assert", "assess", "asset",
    "assign", "assist", "associate", "assume", "assure", "astonish", "astound", "astray",
    "athlete", "atlas", "atmosphere", "atomic", "attach", "attain", "attempt", "attend",
    "attention", "attentive", "attest", "attitude", "attract", "attribute", "auction",
    "audacious", "audible", "audience", "audit", "augment", "august", "authentic",
    "author", "authorize", "automate", "automatic", "autonomous", "autumn", "available",
    "avalanche", "avenue", "average", "avert", "avoid", "await", "awake", "award",
    "aware", "awesome", "awful", "awkward", "backbone", "backdrop", "background",
    "backward", "balance", "ballad", "ballot", "bamboo", "banana", "banish", "bankrupt",
    "banner", "banquet", "baptism", "barbarian", "barbed", "bare", "barely", "bargain",
    "barrel", "barren", "barrier", "barter", "basement", "basic", "basically", "basin",
    "basis", "basket", "batch", "bathe", "battery", "battle", "beacon", "bearing",
    "beast", "beaten", "beautiful", "beauty", "become", "before", "began", "begin",
    "behalf", "behave", "behind", "being", "belief", "believe", "belong", "beloved",
    "below", "beneath", "beneficial", "benefit", "benevolent", "bent", "beside",
    "besides", "bestow", "betray", "better", "between", "beverage", "beware", "beyond",
    "biased", "bicycle", "bilateral", "billion", "binary", "binding", "biography",
    "biological", "bizarre", "blacksmith", "blade", "blame", "bland", "blank",
    "blanket", "blast", "blatant", "blazing", "bleak", "blend", "bless", "blessing",
    "blind", "blink", "bliss", "blissful", "blizzard", "blockade", "bloody", "bloom",
    "blossom", "blunder", "blunt", "blurred", "blush", "board", "boast", "boat",
    "bold", "bolt", "bond", "bonus", "bookmark", "boost", "border", "boring", "borrow",
    "botanical", "bother", "bottle", "bottom", "boulder", "bounce", "bound", "boundary",
    "boundless", "bountiful", "bouquet", "bourgeois", "bracket", "brain", "branch",
    "brand", "brass", "brave", "bravery", "breach", "bread", "breadth", "break",
    "breakthrough", "breathe", "breeze", "brevity", "brick", "bridal", "bridge",
    "brief", "bright", "brilliant", "bring", "brink", "brisk", "brittle", "broad",
    "broadcast", "broken", "bronze", "brook", "brother", "brought", "brush", "brutal",
    "bubble", "budget", "buffer", "build", "buildup", "bulge", "bulk", "bullet",
    "bundle", "burden", "bureau", "bureaucrat", "burglar", "burial", "buried", "burn",
    "burst", "business", "bustle", "button", "buyer", "bypass", "cabin", "cabinet",
    "cable", "cache", "cactus", "cadet", "calculate", "calendar", "caliber", "calibrate",
    "calm", "calorie", "camouflage", "campaign", "campus", "canal", "cancel", "cancer",
    "candid", "candidate", "candle", "candor", "canvas", "canyon", "capable", "capacity",
    "capital", "capitalism", "captain", "captive", "capture", "caravan", "carbon",
    "cardinal", "career", "careful", "cargo", "carnival", "carpet", "carrier", "carry",
    "cartel", "cartoon", "carve", "cascade", "cashier", "casual", "catalog", "catalyst",
    "catastrophe", "catch", "category", "cathedral", "cattle", "caught", "causal",
    "cause", "caution", "cautious", "cavalry", "cease", "ceiling", "celebrate",
    "celebrity", "celestial", "cellar", "cement", "cemetery", "censor", "census",
    "center", "central", "century", "ceramic", "ceremony", "certain", "certainty",
    "certificate", "certify", "chain", "chair", "chairman", "challenge", "chamber",
    "champion", "chance", "change", "channel", "chaos", "chapter", "character",
    "characteristic", "characterize", "charcoal", "charge", "charisma", "charitable",
    "charity", "charm", "charming", "chart", "charter", "chase", "chasm", "chatter",
    "cheap", "cheat", "check", "cheer", "cheerful", "cheese", "chef", "chemical",
    "chemistry", "cherish", "cherry", "chess", "chest", "chew", "chicken", "chief",
    "child", "childhood", "chill", "chilly", "chime", "chimney", "choice", "choir",
    "choke", "choose", "chop", "chore", "chorus", "chosen", "chronic", "chronicle",
    "chuckle", "chunk", "church", "cinema", "cipher", "circle", "circuit", "circular",
    "circulate", "circumference", "circumstance", "circus", "cite", "citizen", "citrus",
    "civic", "civil", "civilian", "civilization", "civilize", "claim", "clamp",
    "clamor", "clap", "clarify", "clarity", "clash", "clasp", "class", "classic",
    "classification", "classify", "classroom", "clause", "claw", "clay", "clean",
    "cleanse", "clear", "clearance", "clearly", "clench", "clergy", "clerk", "clever",
    "click", "client", "cliff", "climate", "climax", "climb", "cling", "clinic",
    "clinical", "clink", "clip", "cloak", "clock", "clockwise", "clog", "clone",
    "close", "closely", "closer", "closet", "cloth", "clothe", "cloud", "cloudy",
    "clover", "clown", "club", "clue", "clumsy", "cluster", "clutch", "coach",
    "coal", "coalition", "coarse", "coast", "coastal", "coat", "coax", "cobalt",
    "cobra", "cocaine", "code", "coerce", "coercion", "coffee", "coffin", "cognitive",
    "coherent", "cohesion", "coil", "coin", "coincide", "coincidence", "cold",
    "collaborate", "collaboration", "collapse", "collar", "colleague", "collect",
    "collection", "collective", "collector", "college", "collegiate", "collide",
    "collision", "colonial", "colonist", "colonize", "colony", "color", "colorful",
    "colossal", "column", "combat", "combination", "combine", "combustion", "comedy",
    "comet", "comfort", "comfortable", "comic", "coming", "comma", "command", "commander",
    "commemorate", "commence", "commend", "comment", "commentary", "commerce", "commercial",
    "commission", "commissioner", "commit", "commitment", "committee", "commodity",
    "common", "commonly", "commonplace", "commonwealth", "commotion", "communal",
    "communicate", "communication", "communion", "communism", "communist", "community",
    "commute", "compact", "companion", "companionship", "company", "comparable",
    "comparative", "compare", "comparison", "compartment", "compass", "compassion",
    "compassionate", "compatible", "compel", "compensate", "compensation", "compete",
    "competence", "competent", "competition", "competitive", "competitor", "compilation",
    "compile", "complacent", "complain", "complaint", "complement", "complementary",
    "complete", "completely", "completion", "complex", "complexity", "compliance",
    "complicate", "complicated", "complication", "compliment", "comply", "component",
    "compose", "composer", "composite", "composition", "compound", "comprehend",
    "comprehension", "comprehensive", "compress", "compression", "comprise", "compromise",
    "compulsory", "compute", "computer", "comrade", "concave", "conceal", "concede",
    "conceit", "conceive", "concentrate", "concentration", "concept", "conception",
    "concern", "concerned", "concert", "concerto", "concession", "concise", "conclude",
    "conclusion", "conclusive", "concoct", "concrete", "concur", "concurrent", "condemn",
    "condensation", "condense", "condition", "conditional", "condolence", "condone",
    "conduct", "conductor", "cone", "confederate", "confederation", "confer", "conference",
    "confess", "confession", "confide", "confidence", "confident", "confidential",
    "confine", "confined", "confinement", "confirm", "confirmation", "confiscate",
    "conflict", "conform", "conformity", "confound", "confront", "confrontation",
    "confuse", "confused", "confusion", "congeal", "congenial", "congest", "congratulate",
    "congratulations", "congregate", "congregation", "congress", "congressional",
    "congruent", "conical", "conjecture", "conjunction", "connect", "connection",
    "conquer", "conqueror", "conquest", "conscience", "conscientious", "conscious",
    "consciousness", "consecutive", "consensus", "consent", "consequence", "consequent",
    "consequently", "conservation", "conservative", "conserve", "consider", "considerable",
    "considerate", "consideration", "consist", "consistency", "consistent", "consolation",
    "console", "consolidate", "consonant", "conspicuous", "conspiracy", "conspirator",
    "conspire", "constant", "constantly", "constellation", "consternation", "constituent",
    "constitute", "constitution", "constitutional", "constrain", "constraint", "constrict",
    "construct", "construction", "constructive", "construe", "consul", "consulate",
    "consult", "consultant", "consultation", "consume", "consumer", "consumption",
    "contact", "contagious", "contain", "container", "contaminate", "contamination",
    "contemplate", "contemplation", "contemporary", "contempt", "contemptuous", "contend",
    "content", "contention", "contentment", "contest", "contestant", "context", "continent",
    "continental", "contingency", "contingent", "continual", "continually", "continuation",
    "continue", "continuity", "continuous", "continuously", "contour", "contraband",
    "contract", "contraction", "contractor", "contradict", "contradiction", "contradictory",
    "contrary", "contrast", "contribute", "contribution", "contributor", "contrive",
    "control", "controversial", "controversy", "convene", "convenience", "convenient",
    "convention", "conventional", "converge", "convergence", "conversation", "converse",
    "conversion", "convert", "convex", "convey", "convict", "conviction", "convince",
    "convocation", "convoy", "cooperate", "cooperation", "cooperative", "coordinate",
    "coordination", "coordinator", "cope", "copious", "copper", "coral", "cord",
    "cordial", "core", "cork", "corn", "corner", "corollary", "coronation", "corporate",
    "corporation", "corps", "corpse", "correct", "correction", "correlate", "correlation",
    "correspond", "correspondence", "correspondent", "corresponding", "corridor", "corrode",
    "corrupt", "corruption", "cosmic", "cosmos", "cost", "costly", "costume", "cottage",
    "cotton", "couch", "cough", "could", "council", "councilor", "counsel", "counselor",
    "count", "counter", "counteract", "counterpart", "countess", "countless", "country",
    "countryside", "county", "coup", "couple", "coupon", "courage", "courageous",
    "courier", "course", "court", "courteous", "courtesy", "courtship", "courtyard",
    "cousin", "cove", "covenant", "cover", "coverage", "covert", "covet", "coward",
    "cowardice", "cowboy", "cower", "crab", "crack", "cradle", "craft", "craftsman",
    "crag", "cram", "cramp", "crane", "crank", "crash", "crate", "crater", "crave",
    "crawl", "craze", "crazy", "creak", "cream", "crease", "create", "creation",
    "creative", "creativity", "creator", "creature", "credence", "credentials", "credibility",
    "credible", "credit", "creditor", "creed", "creek", "creep", "cremate", "crescent",
    "crest", "crevice", "crew", "crib", "cricket", "crime", "criminal", "crimson",
    "cringe", "cripple", "crisis", "crisp", "criterion", "critic", "critical", "criticism",
    "criticize", "critique", "croak", "crochet", "crocodile", "crook", "crooked",
    "crop", "cross", "crossroads", "crouch", "crow", "crowd", "crowded", "crown",
    "crucial", "crude", "cruel", "cruelty", "cruise", "crumb", "crumble", "crumple",
    "crunch", "crusade", "crusader", "crush", "crust", "crutch", "crux", "crystal",
    "crystallize", "cub", "cube", "cubic", "cuckoo", "cucumber", "cuddle", "cuff",
    "culminate", "culmination", "culpable", "culprit", "cult", "cultivate", "cultivation",
    "cultural", "culture", "cultured", "cumbersome", "cumulative", "cunning", "cupboard",
    "curb", "cure", "curfew", "curiosity", "curious", "curl", "currency", "current",
    "currently", "curriculum", "curry", "curse", "cursive", "cursor", "cursory",
    "curt", "curtail", "curtain", "curve", "curved", "cushion", "custodian", "custody",
    "custom", "customary", "customer", "customs", "cycle", "cyclic", "cyclone",
    "cylinder", "cylindrical", "cynic", "cynical", "cynicism",
])

# Nouns (2000+)
mega_words.extend([
    "abandon", "abbey", "abbot", "abdomen", "ability", "ablaze", "abolition", "abortion",
    "abrasion", "absence", "absorption", "abstinence", "abundance", "academy", "accent",
    "acceptance", "access", "accessory", "accident", "accommodation", "accord", "accordion",
    "account", "accountant", "accumulation", "accuracy", "accusation", "achievement",
    "acid", "acknowledgment", "acorn", "acquaintance", "acquisition", "acre", "acrobat",
    "action", "activation", "activist", "activity", "actor", "actress", "adaptation",
    "addiction", "addition", "address", "adherence", "adhesive", "adjective", "adjustment",
    "administration", "administrator", "admiral", "admiration", "admission", "adolescence",
    "adolescent", "adoption", "adoration", "adult", "adulthood", "advancement", "advantage",
    "advent", "adventure", "adventurer", "adverb", "adversary", "adversity", "advertisement",
    "advertising", "advice", "adviser", "advisor", "advocacy", "advocate", "aerial",
    "affair", "affection", "affiliate", "affiliation", "affinity", "affirmation", "affliction",
    "affluence", "afternoon", "afterthought", "agency", "agenda", "agent", "aggravation",
    "aggression", "agility", "agitation", "agony", "agreement", "agriculture", "aide",
    "ailment", "aircraft", "airfield", "airline", "airplane", "airport", "aisle",
    "alarm", "album", "alchemy", "alcohol", "alcove", "alder", "alderman", "ale",
    "alert", "algebra", "alibi", "alien", "alignment", "alimony", "allegation", "allegiance",
    "allegory", "alley", "alliance", "alligator", "allocation", "allowance", "alloy",
    "allusion", "ally", "almanac", "almond", "alphabet", "altar", "alteration", "altercation",
    "alternative", "altitude", "aluminum", "amalgamation", "amateur", "amazement", "ambassador",
    "amber", "ambiguity", "ambition", "ambulance", "ambush", "amendment", "amenity",
    "ammunition", "amnesty", "amount", "amplification", "amplifier", "amplitude", "amusement",
    "analogy", "analysis", "analyst", "anarchy", "anatomy", "ancestor", "ancestry",
    "anchor", "anchorage", "ancient", "android", "anecdote", "angel", "anger", "angle",
    "angler", "anguish", "animal", "animation", "animosity", "ankle", "anklet", "annals",
    "annex", "annexation", "anniversary", "announcement", "announcer", "annoyance",
    "annual", "annuity", "anomaly", "anonymity", "answer", "ant", "antagonism", "antagonist",
    "antecedent", "antelope", "antenna", "anthem", "anthology", "anthropology", "antibiotic",
    "anticipation", "antidote", "antipathy", "antiquary", "antiquity", "antithesis",
    "antler", "anxiety", "apartment", "apathy", "aperture", "apex", "apology", "apostle",
    "apparatus", "apparel", "apparition", "appeal", "appearance", "appendix", "appetite",
    "applause", "apple", "appliance", "applicant", "application", "appointment", "appraisal",
    "appreciation", "apprehension", "apprentice", "apprenticeship", "approach", "approbation",
    "appropriation", "approval", "approximation", "apricot", "apron", "aptitude", "aquarium",
    "aqueduct", "arbiter", "arbitration", "arbitrator", "arbor", "arcade", "arch",
    "archaeologist", "archaeology", "archbishop", "archery", "architect", "architecture",
    "archive", "ardor", "arena", "argument", "aristocracy", "aristocrat", "arithmetic",
    "armament", "armchair", "armistice", "armor", "armory", "armpit", "aroma", "arousal",
    "arrangement", "array", "arrears", "arrest", "arrival", "arrogance", "arrow", "arsenal",
    "arson", "artery", "article", "articulation", "artifact", "artifice", "artist",
    "artisan", "ascendancy", "ascent", "asceticism", "ash", "ashtray", "aspect", "asphalt",
    "aspiration", "aspirin", "assassination", "assassin", "assault", "assembly", "assent",
    "assertion", "assessment", "asset", "assignment", "assimilation", "assistance",
    "assistant", "associate", "association", "assortment", "assumption", "assurance",
    "astonishment", "astrologer", "astrology", "astronaut", "astronomer", "astronomy",
    "asylum", "athlete", "athletics", "atlas", "atmosphere", "atom", "atrocity", "attachment",
    "attainment", "attempt", "attendance", "attendant", "attention", "attic", "attire",
    "attitude", "attorney", "attraction", "attribute", "auction", "auctioneer", "audacity",
    "audience", "audio", "audit", "audition", "auditor", "auditorium", "aunt", "aura",
    "auspices", "austerity", "authenticity", "author", "authority", "authorization",
    "authorship", "autobiography", "autocracy", "autocrat", "autograph", "automation",
    "automobile", "autonomy", "autopsy", "autumn", "availability", "avalanche", "avarice",
    "avenger", "avenue", "average", "aversion", "aviation", "aviator", "avidity",
    "avocado", "avocation", "avowal", "awakening", "award", "awareness", "awe", "axis",
    "axle", "baboon", "bachelor", "background", "backpack", "backup", "bacon", "bacterium",
    "badge", "badger", "badminton", "baggage", "bagpipe", "bail", "bailiff", "bait",
    "baker", "bakery", "balance", "balcony", "bald", "baldness", "bale", "ball",
    "ballad", "ballet", "balloon", "ballot", "balm", "bamboo", "banana", "band",
    "bandage", "bandit", "bandwidth", "banishment", "banister", "banjo", "bank",
    "banker", "banking", "bankruptcy", "banner", "banquet", "bantam", "banter", "baptism",
    "bar", "barbarian", "barbarism", "barbarity", "barbecue", "barber", "bard", "bargain",
    "barge", "baritone", "bark", "barley", "barn", "barometer", "baron", "baroness",
    "barrack", "barracks", "barrage", "barrel", "barren", "barrenness", "barricade",
    "barrier", "barrister", "barroom", "barrow", "bartender", "barter", "base", "baseball",
    "baseline", "basement", "bash", "bashfulness", "basin", "basis", "basket", "basketball",
    "bass", "bastard", "bastion", "bat", "batch", "bath", "bathe", "bathroom", "bathtub",
    "battalion", "batter", "battery", "battle", "battlefield", "battleground", "battleship",
    "bay", "bayonet", "bazaar", "beach", "beacon", "bead", "beak", "beam", "bean",
    "bear", "beard", "bearer", "bearing", "beast", "beat", "beating", "beatitude",
    "beau", "beauty", "beaver", "beck", "bed", "bedding", "bedroom", "bedside", "bedspread",
    "bee", "beef", "beehive", "beer", "beet", "beetle", "befell", "beggar", "begging",
    "beginning", "behalf", "behavior", "beheading", "behest", "being", "belated",
    "belief", "believer", "bell", "belligerent", "bellow", "belly", "belonging", "beloved",
    "belt", "bench", "benchmark", "bend", "benediction", "benefactor", "beneficiary",
    "benefit", "benevolence", "bent", "bequeath", "bequest", "berry", "berth", "beseech",
    "beset", "beside", "besiege", "best", "bestowal", "bet", "betrayal", "betrothal",
    "beverage", "bevy", "bewilderment", "bias", "bib", "bible", "bibliography", "bicycle",
    "bid", "bidder", "bidding", "bifurcation", "bigamy", "bigot", "bigotry", "bike",
    "bilateral", "bile", "bilge", "bill", "billet", "billiards", "billion", "billionaire",
    "billow", "bin", "bind", "binding", "binge", "binoculars", "biochemistry", "biodiversity",
    "biographer", "biography", "biologist", "biology", "biosphere", "birch", "bird",
    "birth", "birthday", "birthplace", "birthright", "biscuit", "bishop", "bishopric",
    "bison", "bit", "bite", "biting", "bitter", "bitterness", "bittersweet", "bizarre",
    "black", "blackberry", "blackbird", "blackboard", "blackmail", "blackness", "blackout",
    "blacksmith", "blade", "blame", "blanket", "blasphemy", "blast", "blaze", "bleach",
    "bleakness", "bleeding", "blemish", "blend", "blessing", "blight", "blind", "blindness",
    "blink", "bliss", "blister", "blizzard", "bloat", "blob", "bloc", "block", "blockade",
    "blockage", "blockhead", "blonde", "blood", "bloodshed", "bloodstream", "bloom",
    "blossom", "blot", "blotch", "blouse", "blow", "blowout", "blubber", "bludgeon",
    "blue", "bluebell", "blueberry", "bluebird", "blueprint", "bluff", "blunder",
    "bluntness", "blur", "blush", "boar", "board", "boarder", "boarding", "boardroom",
    "boast", "boat", "boathouse", "boatman", "bob", "bobbin", "body", "bodyguard",
    "bog", "bogey", "boil", "boiler", "boiling", "boldness", "bole", "bolt", "bomb",
    "bombardment", "bomber", "bombing", "bond", "bondage", "bonding", "bone", "bonfire",
    "bonnet", "bonus", "book", "bookcase", "bookkeeper", "bookkeeping", "booklet",
    "bookmark", "bookseller", "bookshelf", "bookshop", "bookstore", "boom", "boon",
    "boor", "boost", "boot", "booth", "booty", "booze", "border", "borderland", "borderline",
    "bore", "boredom", "borough", "bosom", "boss", "botanical", "botanist", "botany",
    "botch", "both", "bother", "bottle", "bottleneck", "bottom", "boudoir", "bough",
    "boulder", "boulevard", "bounce", "bound", "boundary", "bounty", "bouquet", "bourgeois",
    "bourgeoisie", "bout", "boutique", "bow", "bowel", "bower", "bowl", "box", "boxer",
    "boxing", "boy", "boycott", "boyfriend", "boyhood", "brace", "bracelet", "bracket",
    "brag", "braggart", "braid", "brain", "brainstorm", "brake", "bramble", "bran",
    "branch", "brand", "brandish", "brandy", "brass", "brat", "brave", "bravery",
    "brawl", "brawn", "brazen", "breach", "bread", "breadth", "breadwinner", "break",
    "breakage", "breakdown", "breaker", "breakfast", "breaking", "breakout", "breakthrough",
    "breakup", "breakwater", "breast", "breastplate", "breath", "breathe", "breather",
    "breathing", "bred", "breech", "breed", "breeder", "breeding", "breeze", "brethren",
    "brevity", "brew", "brewer", "brewery", "brewing", "bribe", "bribery", "brick",
    "brickwork", "bridal", "bride", "bridegroom", "bridesmaid", "bridge", "bridle",
    "brief", "briefcase", "briefing", "briefness", "brier", "brigade", "brigadier",
    "brigand", "bright", "brightness", "brilliance", "brim", "brine", "brink", "briskness",
    "bristle", "brittle", "broach", "broad", "broadcast", "broadcaster", "broadcasting",
    "broadside", "broadside", "brocade", "broccoli", "brochure", "brogue", "broil",
    "broker", "brokerage", "bronze", "brooch", "brood", "brook", "broom", "broth",
    "brothel", "brother", "brotherhood", "brow", "browbeat", "brown", "browse", "browser",
    "bruise", "brunch", "brunette", "brunt", "brush", "brushwood", "brutal", "brutality",
    "brute", "bubble", "buccaneer", "buck", "bucket", "buckle", "buckwheat", "bud",
    "buddha", "buddhism", "buddhist", "buddy", "budge", "budget", "buff", "buffalo",
    "buffer", "buffet", "buffoon", "bug", "buggy", "bugle", "build", "builder", "building",
    "buildup", "bulb", "bulge", "bulk", "bull", "bulldog", "bulldozer", "bullet",
    "bulletin", "bullion", "bullock", "bully", "bulwark", "bum", "bumblebee", "bump",
    "bumper", "bunch", "bundle", "bungalow", "bungle", "bungler", "bunk", "bunker",
    "bunny", "buoy", "buoyancy", "burden", "bureau", "bureaucracy", "bureaucrat", "burglar",
    "burglary", "burial", "burlesque", "burn", "burner", "burnish", "burnout", "burrow",
    "burst", "bury", "bus", "bush", "bushel", "business", "businessman", "businesswoman",
    "bust", "bustle", "busy", "butcher", "butchery", "butler", "butt", "butter", "buttercup",
    "butterfly", "buttermilk", "butterscotch", "button", "buttonhole", "buttress",
    "buyer", "buzz", "buzzard", "buzzer", "bypass", "byproduct", "bystander", "byway",
    "byword", "cab", "cabal", "cabbage", "cabin", "cabinet", "cable", "caboose", "cache",
    "cackle", "cactus", "cadet", "cadre", "cafe", "cafeteria", "caffeine", "cage",
    "cake", "calamity", "calcium", "calculate", "calculation", "calculator", "calculus",
    "caldron", "calendar", "calf", "caliber", "calibration", "calico", "call", "caller",
    "calling", "callous", "callousness", "calm", "calmness", "calorie", "calumny",
    "camaraderie", "camel", "cameo", "camera", "cameraman", "camouflage", "camp",
    "campaign", "campaigner", "camper", "campfire", "campground", "campus", "can",
    "canal", "canary", "cancel", "cancellation", "cancer", "candid", "candidacy",
    "candidate", "candle", "candlestick", "candor", "candy", "cane", "canine", "canister",
    "canker", "cannabis", "cannibal", "cannibalism", "cannon", "cannonade", "cannonball",
    "canoe", "canon", "canopy", "cant", "canteen", "canter", "canvas", "canvass",
    "canyon", "cap", "capability", "capable", "capacity", "cape", "caper", "capital",
    "capitalism", "capitalist", "capitalization", "capitol", "capitulation", "caprice",
    "capsize", "capsule", "captain", "captaincy", "caption", "captivation", "captive",
    "captivity", "captor", "capture", "car", "caravan", "carbine", "carbohydrate",
    "carbon", "carbonate", "carburetor", "carcass", "card", "cardboard", "cardiac",
    "cardinal", "care", "career", "carefree", "careful", "careless", "carelessness",
    "caress", "caretaker", "cargo", "caribou", "caricature", "caries", "carload",
    "carnage", "carnal", "carnation", "carnival", "carnivore", "carnivorous", "carol",
    "carousel", "carp", "carpenter", "carpentry", "carpet", "carriage", "carrier",
    "carrion", "carrot", "carry", "cart", "cartage", "carter", "cartilage", "carton",
    "cartoon", "cartoonist", "cartridge", "cartwheel", "carve", "carver", "carving",
    "cascade", "case", "casement", "cash", "cashew", "cashier", "casing", "casino",
    "cask", "casket", "cassette", "cast", "caste", "caster", "casting", "castle",
    "castor", "casual", "casualty", "cat", "cataclysm", "catalog", "catalogue", "catalyst",
    "catapult", "cataract", "catastrophe", "catch", "catcher", "catching", "catchword",
    "catechism", "category", "cater", "caterer", "catering", "caterpillar", "cathedral",
    "catholic", "catholicism", "cattle", "cauldron", "cauliflower", "caulk", "causal",
    "causality", "causation", "cause", "causeway", "caustic", "caution", "cautious",
    "cavalcade", "cavalier", "cavalry", "cavalryman", "cave", "cavern", "cavernous",
    "cavity", "cayenne", "cease", "ceasefire", "ceaseless", "cedar", "cede", "ceiling",
    "celebrant", "celebrate", "celebration", "celebrity", "celerity", "celery", "celestial",
    "celibacy", "cell", "cellar", "cellist", "cello", "cellophane", "cellular", "celluloid",
    "cellulose", "cement", "cemetery", "censor", "censorship", "censure", "census",
    "cent", "centenary", "centennial", "center", "centerpiece", "centigrade", "centimeter",
    "centipede", "central", "centralization", "centre", "centrifugal", "century",
    "ceramic", "cereal", "cerebral", "ceremonial", "ceremonious", "ceremony", "certainty",
    "certificate", "certification", "certify", "certitude", "cessation", "cession",
    "chafe", "chaff", "chagrin", "chain", "chainsaw", "chair", "chairman", "chairmanship",
    "chairperson", "chairwoman", "chaise", "chalet", "chalice", "chalk", "chalkboard",
    "challenge", "challenger", "chamber", "chamberlain", "chambermaid", "chameleon",
    "chamois", "champ", "champagne", "champion", "championship", "chance", "chancel",
    "chancellor", "chandelier", "chandler", "change", "changeable", "channel", "chant",
    "chaos", "chaotic", "chap", "chapel", "chaperon", "chaperone", "chaplain", "chaplaincy",
    "chapter", "char", "character", "characteristic", "characterization", "charcoal",
    "charge", "charger", "chariot", "charioteer", "charisma", "charismatic", "charitable",
    "charity", "charlatan", "charm", "charmer", "chart", "charter", "charwoman", "chase",
    "chaser", "chasm", "chassis", "chaste", "chastise", "chastisement", "chastity",
    "chat", "chateau", "chattel", "chatter", "chatterbox", "chauffeur", "chauvinism",
    "cheap", "cheapen", "cheapness", "cheat", "cheater", "check", "checkbook", "checker",
    "checkerboard", "checking", "checklist", "checkmate", "checkout", "checkpoint",
    "checkroom", "checkup", "cheek", "cheekbone", "cheer", "cheerful", "cheerfulness",
    "cheerleader", "cheerless", "cheese", "cheetah", "chef", "chemical", "chemist",
    "chemistry", "cheque", "cherish", "cherry", "cherub", "chess", "chessboard", "chest",
    "chestnut", "chevron", "chew", "chewing", "chic", "chicanery", "chick", "chicken",
    "chickpea", "chicory", "chide", "chief", "chieftain", "chiffon", "chilblain",
    "child", "childbearing", "childbirth", "childhood", "childish", "childishness",
    "childless", "childlike", "children", "chill", "chilli", "chilliness", "chilly",
    "chime", "chimney", "chimpanzee", "chin", "china", "chinaware", "chink", "chip",
    "chipmunk", "chiropractor", "chirp", "chisel", "chivalry", "chive", "chloride",
    "chlorine", "chloroform", "chlorophyll", "chocolate", "choice", "choir", "choirmaster",
    "choke", "choker", "cholera", "cholesterol", "choose", "chooser", "chop", "chopper",
    "chopping", "choppy", "chopstick", "choral", "chord", "chore", "choreographer",
    "choreography", "chorister", "chortle", "chorus", "chosen", "chowder", "christen",
    "christening", "christian", "christianity", "christmas", "chrome", "chromium",
    "chromosome", "chronic", "chronicle", "chronicler", "chronological", "chronology",
    "chrysalis", "chrysanthemum", "chubby", "chuck", "chuckle", "chum", "chunk", "church",
    "churchgoer", "churchman", "churchyard", "churn", "chute", "cider", "cigar",
    "cigarette", "cinch", "cinder", "cinema", "cinnamon", "cipher", "circle", "circuit",
    "circuitous", "circular", "circulate", "circulation", "circumference", "circumlocution",
    "circumnavigate", "circumnavigation", "circumscribe", "circumspect", "circumspection",
    "circumstance", "circumstantial", "circumvent", "circus", "cirrhosis", "cistern",
    "citadel", "citation", "cite", "citizen", "citizenry", "citizenship", "citric",
    "citron", "citrus", "city", "civic", "civil", "civilian", "civility", "civilization",
    "clack", "claim", "claimant", "clairvoyance", "clam", "clamber", "clamminess",
    "clammy", "clamor", "clamp", "clan", "clandestine", "clang", "clank", "clap",
    "clapper", "claptrap", "claret", "clarification", "clarify", "clarinet", "clarity",
    "clash", "clasp", "class", "classic", "classical", "classification", "classify",
    "classmate", "classroom", "clatter", "clause", "claustrophobia", "clavicle", "claw",
    "clay", "clean", "cleaner", "cleaning", "cleanliness", "cleanness", "cleanse",
    "cleanser", "cleanup", "clear", "clearance", "clearing", "clearness", "cleat",
    "cleavage", "cleave", "cleaver", "clef", "cleft", "clemency", "clench", "clergy",
    "clergyman", "cleric", "clerical", "clerk", "clever", "cleverness", "click", "client",
    "clientele", "cliff", "climate", "climax", "climb", "climber", "climbing", "clime",
    "clinch", "cling", "clinic", "clinical", "clink", "clip", "clipboard", "clipper",
    "clipping", "clique", "cloak", "cloakroom", "clock", "clockwise", "clockwork",
    "clod", "clog", "cloister", "clone", "close", "closeness", "closet", "closeup",
    "closing", "closure", "clot", "cloth", "clothe", "clothes", "clothesline", "clothing",
    "cloud", "cloudburst", "cloudless", "cloudy", "clout", "clove", "clover", "clown",
    "cloy", "club", "clubhouse", "clubroom", "cluck", "clue", "clump", "clumsiness",
    "clumsy", "cluster", "clutch", "clutter", "coach", "coachman", "coagulate", "coagulation",
    "coal", "coalesce", "coalfield", "coalition", "coalmine", "coalminer", "coarse",
    "coarsen", "coarseness", "coast", "coastal", "coaster", "coastguard", "coastline",
    "coat", "coating", "coax", "cob", "cobalt", "cobble", "cobbler", "cobblestone",
    "cobra", "cobweb", "cocaine", "cock", "cockatoo", "cockerel", "cockle", "cockney",
    "cockpit", "cockroach", "cockscomb", "cocktail", "cocky", "cocoa", "coconut",
    "cocoon", "code", "codeine", "codfish", "codification", "codify", "coeducation",
    "coefficient", "coerce", "coercion", "coexist", "coexistence", "coffee", "coffeehouse",
    "coffer", "coffin", "cog", "cogency", "cogent", "cogitate", "cogitation", "cognac",
    "cognate", "cognition", "cognizance", "cognizant", "cogwheel", "cohabit", "cohabitation",
    "cohere", "coherence", "coherent", "cohesion", "cohesive", "cohort", "coil", "coin",
    "coinage", "coincide", "coincidence", "coincident", "coincidental", "coke", "cold",
    "coldness", "coleslaw", "colic", "coliseum", "collaborate", "collaboration",
    "collaborator", "collage", "collapse", "collar", "collarbone", "collate", "collateral",
    "collation", "colleague", "collect", "collection", "collective", "collector",
    "college", "collegian", "collegiate", "collide", "collie", "collier", "colliery",
    "collision", "collocation", "colloquial", "colloquialism", "colloquy", "collusion",
    "colon", "colonel", "colonial", "colonialism", "colonist", "colonization", "colonize",
    "colonnade", "colony", "color", "coloration", "colorblind", "colored", "colorful",
    "coloring", "colorless", "colossal", "colossus", "colt", "column", "columnist",
    "coma", "comb", "combat", "combatant", "combination", "combine", "combustible",
    "combustion", "come", "comeback", "comedian", "comedy", "comeliness", "comely",
    "comer", "comet", "comeuppance", "comfort", "comfortable", "comforter", "comic",
    "comical", "comma", "command", "commandant", "commandeer", "commander", "commanding",
    "commandment", "commando", "commemorate", "commemoration", "commemorative", "commence",
    "commencement", "commend", "commendable", "commendation", "commensurable", "commensurate",
    "comment", "commentary", "commentator", "commerce", "commercial", "commercialism",
    "commercialize", "commingle", "commiserate", "commiseration", "commissar", "commissariat",
    "commissary", "commission", "commissioner", "commit", "commitment", "committal",
    "committee", "commode", "commodious", "commodity", "commodore", "common", "commonalty",
    "commoner", "commonly", "commonplace", "commons", "commonsense", "commonwealth",
    "commotion", "communal", "commune", "communicant", "communicate", "communication",
    "communicative", "communion", "communique", "communism", "communist", "community",
    "commutation", "commute", "commuter", "compact", "companion", "companionable",
    "companionship", "companionway", "company", "comparable", "comparative", "compare",
    "comparison", "compartment", "compass", "compassion", "compassionate", "compatibility",
    "compatible", "compatriot", "compel", "compendium", "compensate", "compensation",
    "compensatory", "compete", "competence", "competent", "competition", "competitive",
    "competitor", "compilation", "compile", "compiler", "complacence", "complacency",
    "complacent", "complain", "complainant", "complaint", "complaisance", "complaisant",
    "complement", "complementary", "complete", "completion", "complex", "complexion",
    "complexity", "compliance", "compliant", "complicate", "complicated", "complication",
    "complicity", "compliment", "complimentary", "comply", "component", "comport",
    "comportment", "compose", "composer", "composite", "composition", "compositor",
    "composure", "compound", "comprehend", "comprehensible", "comprehension", "comprehensive",
    "compress", "compression", "compressor", "comprise", "compromise", "comptroller",
    "compulsion", "compulsive", "compulsory", "compunction", "computation", "compute",
    "computer", "comrade", "comradeship", "con", "concatenation", "concave", "concavity",
    "conceal", "concealment", "concede", "conceit", "conceited", "conceivable", "conceive",
    "concentrate", "concentration", "concentric", "concept", "conception", "conceptual",
    "concern", "concerned", "concerning", "concert", "concerted", "concertina", "concerto",
    "concession", "concessionaire", "conciliate", "conciliation", "conciliatory", "concise",
    "conciseness", "conclave", "conclude", "conclusion", "conclusive", "concoct",
    "concoction", "concomitant", "concord", "concordance", "concordat", "concourse",
    "concrete", "concretion", "concubine", "concur", "concurrence", "concurrent", "concussion",
    "condemn", "condemnation", "condemnatory", "condensation", "condense", "condenser",
    "condescend", "condescending", "condescension", "condiment", "condition", "conditional",
    "conditioner", "conditioning", "condole", "condolence", "condom", "condominium",
    "condone", "condor", "conduce", "conducive", "conduct", "conduction", "conductor",
    "conduit", "cone", "confection", "confectioner", "confectionery", "confederacy",
    "confederate", "confederation", "confer", "conference", "confess", "confession",
    "confessional", "confessor", "confetti", "confidant", "confide", "confidence",
    "confident", "confidential", "confidentiality", "confiding", "configuration",
    "confine", "confined", "confinement", "confirm", "confirmation", "confirmatory",
    "confirmed", "confiscate", "confiscation", "conflagration", "conflict", "conflicting",
    "confluence", "conform", "conformable", "conformation", "conformist", "conformity",
    "confound", "confounded", "confront", "confrontation", "confuse", "confused",
    "confusion", "confute", "congeal", "congenial", "congeniality", "congenital",
    "congest", "congestion", "conglomerate", "conglomeration", "congratulate", "congratulation",
    "congregate", "congregation", "congregational", "congress", "congressional", "congressman",
    "congresswoman", "congruence", "congruent", "congruity", "congruous", "conical",
    "conifer", "coniferous", "conjecture", "conjectural", "conjoin", "conjugal",
    "conjugate", "conjugation", "conjunction", "conjunctivitis", "conjuncture", "conjuration",
    "conjure", "conjurer", "conjuror", "conk", "connect", "connection", "connective",
    "connector", "conniption", "connivance", "connive", "connoisseur", "connotation",
    "connote", "connubial", "conquer", "conquering", "conqueror", "conquest", "consanguinity",
    "conscience", "conscientious", "conscious", "consciousness", "conscript", "conscription",
    "consecrate", "consecration", "consecutive", "consensus", "consent", "consequence",
    "consequent", "consequential", "consequently", "conservation", "conservatism",
    "conservative", "conservatoire", "conservatory", "conserve", "consider", "considerable",
    "considerably", "considerate", "consideration", "considering", "consign", "consignee",
    "consignment", "consist", "consistency", "consistent", "consolation", "consolatory",
    "console", "consolidate", "consolidation", "consomme", "consonance", "consonant",
    "consort", "consortium", "conspicuous", "conspiracy", "conspirator", "conspiratorial",
    "conspire", "constable", "constabulary", "constancy", "constant", "constellation",
    "consternation", "constipate", "constipation", "constituency", "constituent",
    "constitute", "constitution", "constitutional", "constrain", "constraint", "constrict",
    "constriction", "construct", "construction", "constructive", "constructor", "construe",
    "consubstantiation", "consul", "consular", "consulate", "consult", "consultant",
    "consultation", "consultative", "consulting", "consume", "consumer", "consumerism",
    "consummate", "consummation", "consumption", "consumptive", "contact", "contagion",
    "contagious", "contain", "container", "containerize", "containment", "contaminant",
    "contaminate", "contamination", "contemplate", "contemplation", "contemplative",
    "contemporaneous", "contemporary", "contempt", "contemptible", "contemptuous",
    "contend", "contender", "content", "contented", "contention", "contentious", "contentment",
    "contest", "contestant", "context", "contextual", "contiguity", "contiguous",
    "continence", "continent", "continental", "contingency", "contingent", "continual",
    "continually", "continuance", "continuation", "continue", "continuity", "continuous",
    "continuously", "continuum", "contort", "contortion", "contortionist", "contour",
    "contraband", "contraception", "contraceptive", "contract", "contraction", "contractor",
    "contractual", "contradict", "contradiction", "contradictory", "contraption",
    "contralto", "contraption", "contrariety", "contrariwise", "contrary", "contrast",
    "contravene", "contravention", "contribute", "contribution", "contributor", "contributory",
    "contrite", "contrition", "contrivance", "contrive", "control", "controller",
    "controversial", "controversy", "controvert", "contumacious", "contumacy", "contumely",
    "contuse", "contusion", "conundrum", "conurbation", "convalesce", "convalescence",
    "convalescent", "convection", "convene", "convenience", "convenient", "convent",
    "convention", "conventional", "conventionality", "conventionalize", "converge",
    "convergence", "convergent", "conversant", "conversation", "conversational",
    "conversationalist", "converse", "conversion", "convert", "converter", "convertible",
    "convex", "convexity", "convey", "conveyance", "conveyor", "convict", "conviction",
    "convince", "convincing", "convivial", "conviviality", "convocation", "convolute",
    "convoluted", "convolution", "convoy", "convulse", "convulsion", "convulsive",
    "coo", "cook", "cookbook", "cooker", "cookery", "cookie", "cooking", "cookout",
    "cool", "coolant", "cooler", "coolheaded", "coolness", "coon", "coop", "cooper",
    "cooperate", "cooperation", "cooperative", "coordinate", "coordination", "coordinator",
    "coot", "cop", "cope", "copier", "copilot", "coping", "copious", "copper", "coppice",
    "copse", "copulate", "copulation", "copy", "copybook", "copycat", "copying", "copyist",
    "copyright", "copywriter", "coquetry", "coquette", "coquettish", "coral", "cord",
    "cordage", "cordial", "cordiality", "cordon", "corduroy", "core", "coriander",
    "cork", "corkscrew", "cormorant", "corn", "cornbread", "corncob", "cornea", "corner",
    "cornerstone", "cornet", "cornfield", "cornflakes", "cornflour", "cornflower",
    "cornice", "cornmeal", "cornstarch", "corny", "corolla", "corollary", "corona",
    "coronary", "coronation", "coroner", "coronet", "corporal", "corporate", "corporation",
    "corporeal", "corps", "corpse", "corpulence", "corpulent", "corpuscle", "corral",
    "correct", "correction", "correctional", "correctness", "correlate", "correlation",
    "correlative", "correspond", "correspondence", "correspondent", "corresponding",
    "corridor", "corroborate", "corroboration", "corroborative", "corrode", "corrosion",
    "corrosive", "corrugate", "corrugated", "corrugation", "corrupt", "corruption",
    "corsage", "corset", "cortege", "cortex", "cortisone", "corvette", "cosine",
    "cosmetic", "cosmic", "cosmogony", "cosmology", "cosmonaut", "cosmopolitan",
    "cosmos", "cost", "costal", "costar", "costliness", "costly", "costume", "cot",
    "cottage", "cottager", "cotton", "cottonseed", "cottonwood", "cottony", "couch",
    "cougar", "cough", "could", "council", "councillor", "councilor", "councilman",
    "councilwoman", "counsel", "counseling", "counsellor", "counselor", "count",
    "countdown", "countenance", "counter", "counteract", "counteraction", "counterattack",
    "counterbalance", "countercharge", "counterclaim", "counterclockwise", "counterculture",
    "counterespionage", "counterfeit", "counterfeiter", "counterfoil", "counterintelligence",
    "countermand", "countermeasure", "countermove", "counteroffensive", "counterpane",
    "counterpart", "counterplot", "counterpoint", "counterpoise", "counterrevolution",
    "counterrevolutionary", "countersign", "countersink", "counterspy", "counterstroke",
    "countervail", "counterweight", "countess", "countless", "countrified", "country",
    "countryman", "countryside", "countrywide", "countrywoman", "county", "coup",
    "coupe", "couple", "couplet", "coupon", "courage", "courageous", "courier", "course",
    "courser", "court", "courteous", "courtesan", "courtesy", "courthouse", "courtier",
    "courtly", "courtship", "courtyard", "cousin", "cove", "covenant", "cover", "coverage",
    "covering", "coverlet", "covert", "coverup", "covet", "covetous", "covetousness",
    "cow", "coward", "cowardice", "cowardly", "cowbell", "cowboy", "cower", "cowgirl",
    "cowherd", "cowhide", "cowl", "coworker", "cowpox", "cowpuncher", "cowrie", "cowshed",
    "cowslip", "coxcomb", "coxswain", "coy", "coyness", "coyote", "crab", "crabbed",
    "crack", "crackdown", "cracked", "cracker", "crackle", "crackpot", "crackup",
    "cradle", "craft", "craftiness", "craftsman", "craftsmanship", "crafty", "crag",
    "craggy", "cram", "cramp", "cramped", "cranberry", "crane", "cranium", "crank",
    "crankcase", "crankshaft", "cranky", "cranny", "crape", "craps", "crash", "crass",
    "crate", "crater", "cravat", "crave", "craven", "craving", "crawfish", "crawl",
    "crawler", "crayfish", "crayon", "craze", "crazy", "creak", "creaky", "cream",
    "creamery", "creamy", "crease", "create", "creation", "creationism", "creative",
    "creativity", "creator", "creature", "creche", "credence", "credential", "credibility",
    "credible", "credit", "creditable", "creditor", "credo", "credulity", "credulous",
    "creed", "creek", "creel", "creep", "creeper", "creepy", "cremate", "cremation",
    "crematorium", "crematory", "creole", "creosote", "crepe", "crept", "crescendo",
    "crescent", "cress", "crest", "crestfallen", "cretaceous", "cretin", "cretonne",
    "crevasse", "crevice", "crew", "crewman", "crib", "cricket", "crier", "crime",
    "criminal", "criminality", "criminology", "crimp", "crimson", "cringe", "crinkle",
    "crinoline", "cripple", "crisis", "crisp", "crispness", "crisscross", "criterion",
    "critic", "critical", "criticism", "criticize", "critique", "critter", "croak",
    "crochet", "crock", "crockery", "crocodile", "crocus", "croft", "crofter", "croissant",
    "crone", "crony", "crook", "crooked", "croon", "crop", "cropper", "croquet",
    "croquette", "cross", "crossbar", "crossbow", "crossbreed", "crosscurrent", "crosscut",
    "crossfire", "crossing", "crosspiece", "crossroad", "crossroads", "crosstown",
    "crosswalk", "crossway", "crosswind", "crosswise", "crossword", "crotch", "crotchet",
    "crotchety", "crouch", "croup", "crouton", "crow", "crowbar", "crowd", "crowded",
    "crown", "crucial", "crucible", "crucifix", "crucifixion", "cruciform", "crucify",
    "crude", "crudeness", "crudity", "cruel", "cruelty", "cruet", "cruise", "cruiser",
    "cruller", "crumb", "crumble", "crumbly", "crummy", "crumpet", "crumple", "crunch",
    "crunchy", "crusade", "crusader", "cruse", "crush", "crusher", "crust", "crustacean",
    "crusty", "crutch", "crux", "cry", "crybaby", "crying", "crypt", "cryptic",
    "cryptogram", "cryptography", "crystal", "crystalline", "crystallization", "crystallize",
    "cub", "cube", "cubic", "cubicle", "cubism", "cubit", "cuckold", "cuckoo", "cucumber",
    "cud", "cuddle", "cuddly", "cudgel", "cue", "cuff", "cuisine", "cul", "culinary",
    "cull", "culminate", "culmination", "culpability", "culpable", "culprit", "cult",
    "cultivate", "cultivation", "cultivator", "cultural", "culture", "cultured", "culvert",
    "cumber", "cumbersome", "cumulative", "cumulus", "cunning", "cup", "cupboard",
    "cupful", "cupidity", "cupola", "cur", "curable", "curate", "curative", "curator",
    "curb", "curbstone", "curd", "curdle", "cure", "curfew", "curio", "curiosity",
    "curious", "curl", "curler", "curlew", "curling", "curly", "curmudgeon", "currant",
    "currency", "current", "currently", "curricle", "curriculum", "currier", "curry",
    "curse", "cursed", "cursive", "cursor", "cursory", "curt", "curtail", "curtailment",
    "curtain", "curtness", "curtsy", "curvature", "curve", "curvilinear", "cushion",
    "cushy", "cusp", "cuspid", "cuspidor", "cuss", "custard", "custodian", "custody",
    "custom", "customary", "customer", "customhouse", "customize", "customs", "cut",
    "cutaneous", "cutaway", "cutback", "cute", "cuteness", "cuticle", "cutlery",
    "cutlet", "cutoff", "cutout", "cutter", "cutthroat", "cutting", "cuttlefish",
    "cutup", "cyanide", "cybernetics", "cycle", "cyclic", "cyclical", "cyclist",
    "cyclone", "cyclotron", "cygnet", "cylinder", "cylindrical", "cymbal", "cynic",
    "cynical", "cynicism", "cynosure", "cypher", "cypress", "cyst", "czar", "czarina",
])

# Add all to set to ensure uniqueness
all_mega = set(mega_words + sum([list(v) for v in current.values()], []))

print(f"\nTotal words after expansion: {len(all_mega)}")

# Categorize
def categorize(words):
    tiers = {"easy": [], "medium": [], "hard": [], "boss": []}
    for w in words:
        l = len(w)
        if l <= 4: tiers["easy"].append(w)
        elif l <= 7: tiers["medium"].append(w)
        elif l <= 10: tiers["hard"].append(w)
        else: tiers["boss"].append(w)
    
    for k in tiers:
        tiers[k] = sorted(set(tiers[k]))
    return tiers

pools = categorize(all_mega)

print(f"\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print(f"Easy   (≤4):  {len(pools['easy'])} words")
print(f"Medium (5-7): {len(pools['medium'])} words")
print(f"Hard   (8-10): {len(pools['hard'])} words")  
print(f"Boss   (11+):  {len(pools['boss'])} words")
print(f"\nTotal: {sum(len(v) for v in pools.values())}")
print(f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

with open('words.json', 'w') as f:
    json.dump(pools, f, indent=2)

print(f"✓ MEGA words.json generated!")
print(f"✓ File size: ~{len(json.dumps(pools)) // 1024}KB")
